spring:
  application:
    name: 'servico-cliente'
  datasource:
    password: <>
    username: <>
    url: jdbc:mysql://authdb.cqk3oq68g2xq.us-east-1.rds.amazonaws.com:3306/authdb?serverTimezone=GMT
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      hibernate:
        ddl: true
        ddl-auto: create

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-234-229-225.compute-1.amazonaws.com:8761/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://2-54-91-46-136.compute-1.amazonaws.com:8088/user

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: <>
      secret-key: <>
    end-point:
        uri-criar: https://sqs.us-east-1.amazonaws.com/124223312961/criar_pedido_status
        uri-atualizar: https://sqs.us-east-1.amazonaws.com/124223312961/atualizar_pedido_status

